use anchor_lang::prelude::*;
#[cfg(not(feature = "no-zk"))]
use anchor_lang::solana_program::{instruction::Instruction, program::invoke};
#[cfg(not(feature = "no-zk"))]
use solana_program::hash::hashv;

// ── Compile-time guard ────────────────────────────────────────────────────────
// `no-zk` skips the CPI to the RISC Zero VerifierRouter entirely.
// It must never be activated without the `testing` feature, which signals
// conscious localnet use. This fires on any of:
//   - `anchor build --features no-zk`          (accidental deploy)
//   - `cargo build-sbf --features no-zk`       (accidental deploy)
// And is suppressed by:
//   - `anchor test --features testing`          (correct localnet usage)
//   - `cargo test --features no-zk`            (unit tests, cfg(test) active)
#[cfg(all(feature = "no-zk", not(feature = "testing"), not(test)))]
compile_error!(
    "Feature 'no-zk' must not be activated directly. \
     For localnet tests use: anchor test --features testing\n\
     For devnet/mainnet builds use: anchor build  (no extra flags)\n\
     Never deploy with 'no-zk' active — it disables all ZK verification."
);

declare_id!("EyjVnweqSt8fNmnF9ugQMPSzT8sRX57K1SnKRqbsNiTs");

// ── RISC Zero Verifier Router (Devnet) ───────────────────────────────────────
// Confirma con: solana account 6JvFfBrvCcWgANKh1Eae9xDq4RC6cfJuBcf71rp2k9Y7 --url devnet
#[cfg(not(feature = "no-zk"))]
const VERIFIER_ROUTER: Pubkey = pubkey!("6JvFfBrvCcWgANKh1Eae9xDq4RC6cfJuBcf71rp2k9Y7");

// Anchor discriminator de la instrucción "verify" = sha256("global:verify")[0..8]
#[cfg(not(feature = "no-zk"))]
const VERIFY_DISCRIMINATOR: [u8; 8] = [133, 161, 141, 48, 120, 198, 88, 150];

// ── AGENT_GUEST_ID ────────────────────────────────────────────────────────────
// SHA-256 del ELF compilado del guest (risc-zero-v2/methods/guest).
// Derivado de image_id_hex en risc-zero-v2/audit_proof.json:
//   "3f358e217f040981da73cf005046746cd06a0cb0c8a045b73cdc7d6f6b0ecfcf"
// Solo proofs generados por este guest exacto son aceptados on-chain.
// ⚠️  Actualizar al recompilar el guest (risc0-build recalcula el hash).
#[cfg(not(feature = "no-zk"))]
const AGENT_GUEST_ID: [u8; 32] = [
    0x3f, 0x35, 0x8e, 0x21, 0x7f, 0x04, 0x09, 0x81,
    0xda, 0x73, 0xcf, 0x00, 0x50, 0x46, 0x74, 0x6c,
    0xd0, 0x6a, 0x0c, 0xb0, 0xc8, 0xa0, 0x45, 0xb7,
    0x3c, 0xdc, 0x7d, 0x6f, 0x6b, 0x0e, 0xcf, 0xcf,
];

// ── AuditJournal (layout fijo, 132 bytes) ─────────────────────────────────────
// Debe coincidir exactamente con lo que commitea el guest en risc-zero-v2.
//   [0..32]    contract_hash    — sha256(contract_bytes)
//   [32..36]   findings_count   — u32 le, número de findings del checker
//   [36..68]   jobspec_hash     — sha256(jobspec_json), debe == job.output_hash
//   [68..100]  findings_hash    — sha256(findings JSON), compromiso sobre hallazgos
//   [100..132] auditor_pubkey   — Solana pubkey del auditor
#[allow(dead_code)]
struct AuditJournal {
    jobspec_hash:   [u8; 32],
    findings_hash:  [u8; 32],   // compromiso on-chain sobre los hallazgos del checker
    auditor_pubkey: [u8; 32],
}

impl AuditJournal {
    fn from_bytes(b: &[u8]) -> Result<Self> {
        require!(b.len() == 132, AgentMarketError::InvalidJournal);
        Ok(Self {
            jobspec_hash:   b[36..68].try_into().unwrap(),
            findings_hash:  b[68..100].try_into().unwrap(),
            auditor_pubkey: b[100..132].try_into().unwrap(),
        })
    }
}

// ── Errores ───────────────────────────────────────────────────────────────────

#[error_code]
pub enum AgentMarketError {
    #[msg("Job is not in Open status")]
    JobNotOpen,
    #[msg("Job has already been claimed")]
    JobAlreadyClaimed,
    #[msg("Caller is not the assigned agent")]
    NotAssignedAgent,
    #[msg("Job is not in PendingVerification status")]
    JobNotPendingVerification,
    #[msg("Result hash does not match expected output hash")]
    HashMismatch,
    #[msg("Job is not in InProgress status")]
    JobNotInProgress,
    #[msg("ZK proof invalid: journal jobspec_hash != job output_hash")]
    ReportHashMismatch,
    #[msg("ZK proof invalid: auditor_pubkey != agent signer")]
    AuditorMismatch,
    #[msg("Journal must be exactly 132 bytes")]
    InvalidJournal,
    #[msg("ZK proof verification failed")]
    ProofInvalid,
    #[msg("Job cannot be cancelled in current state")]
    JobCannotBeCancelled,
    #[msg("Proof was not generated by the authorized guest")]
    InvalidGuestId,
}

// ── Estado ────────────────────────────────────────────────────────────────────

#[derive(AnchorSerialize, AnchorDeserialize, Clone, PartialEq)]
pub enum JobStatus {
    Open,
    InProgress,
    PendingVerification,
    Completed,
    Disputed,
    Cancelled,
}

#[account]
pub struct Job {
    pub client:      Pubkey,
    pub agent:       Option<Pubkey>,
    pub input_hash:  [u8; 32],
    pub output_hash: [u8; 32],
    pub result_hash: [u8; 32],
    pub reward:      u64,
    pub status:      JobStatus,
    pub created_at:  i64,
    pub bump:        u8,
}

// ── Instrucciones ─────────────────────────────────────────────────────────────

#[event]
pub struct JobCancelled {
    pub job_pubkey:      Pubkey,
    pub client:          Pubkey,
    pub reward_returned: u64,
}

#[event]
pub struct JobCreated {
    pub job_pubkey:   Pubkey,
    pub client:       Pubkey,
    pub reward:       u64,
    pub created_at:   i64,
    pub job_spec_url: String,
}

#[program]
pub mod agentmarket {
    use super::*;

    pub fn create_job(
        ctx:          Context<CreateJob>,
        input_hash:   [u8; 32],
        output_hash:  [u8; 32],
        reward:       u64,
        created_at:   i64,
        job_spec_url: String,
    ) -> Result<()> {
        let job = &mut ctx.accounts.job;
        job.client      = ctx.accounts.client.key();
        job.agent       = None;
        job.input_hash  = input_hash;
        job.output_hash = output_hash;
        job.result_hash = [0u8; 32];
        job.reward      = reward;
        job.status      = JobStatus::Open;
        job.created_at  = created_at;
        job.bump        = ctx.bumps.job;

        let cpi_ctx = CpiContext::new(
            ctx.accounts.system_program.to_account_info(),
            anchor_lang::system_program::Transfer {
                from: ctx.accounts.client.to_account_info(),
                to:   ctx.accounts.job.to_account_info(),
            },
        );
        anchor_lang::system_program::transfer(cpi_ctx, reward)?;
        emit!(JobCreated {
            job_pubkey:   ctx.accounts.job.key(),
            client:       ctx.accounts.client.key(),
            reward,
            created_at,
            job_spec_url,
        });
        Ok(())
    }

    pub fn cancel_job(ctx: Context<CancelJob>) -> Result<()> {
        let job = &mut ctx.accounts.job;

        require!(
            job.status == JobStatus::Open ||
            (job.status == JobStatus::InProgress &&
             Clock::get()?.unix_timestamp - job.created_at > 72 * 3600),
            AgentMarketError::JobCannotBeCancelled
        );

        let reward = job.reward;
        job.sub_lamports(reward)?;
        ctx.accounts.client.add_lamports(reward)?;
        job.status = JobStatus::Cancelled;

        emit!(JobCancelled {
            job_pubkey:      ctx.accounts.job.key(),
            client:          ctx.accounts.client.key(),
            reward_returned: reward,
        });
        Ok(())
    }

    pub fn claim_job(ctx: Context<ClaimJob>, _created_at: i64) -> Result<()> {
        let job = &mut ctx.accounts.job;
        require!(job.status == JobStatus::Open, AgentMarketError::JobNotOpen);
        require!(job.agent.is_none(),           AgentMarketError::JobAlreadyClaimed);
        job.agent  = Some(ctx.accounts.agent.key());
        job.status = JobStatus::InProgress;
        Ok(())
    }

    pub fn submit_result(ctx: Context<SubmitResult>, result_hash: [u8; 32]) -> Result<()> {
        let job = &mut ctx.accounts.job;
        require!(job.status == JobStatus::InProgress, AgentMarketError::JobNotInProgress);
        require!(
            job.agent == Some(ctx.accounts.agent.key()),
            AgentMarketError::NotAssignedAgent
        );
        job.result_hash = result_hash;
        job.status      = JobStatus::PendingVerification;
        Ok(())
    }

    /// Verifica un ZK proof de RISC Zero y paga al auditor si es válido.
    ///
    /// El proof garantiza matemáticamente que:
    ///   - El auditor tuvo los contract_bytes (contract_hash)
    ///   - Las reglas de seguridad se ejecutaron sobre esos bytes (findings_hash)
    ///   - El job es el correcto (jobspec_hash == job.output_hash)
    ///   - El pagado es el auditor registrado (auditor_pubkey)
    ///
    /// Argumentos:
    ///   seal            — Groth16 proof serializado: 4 bytes selector + 256 bytes proof
    ///   journal_outputs — 132 bytes del AuditJournal commitado por el guest
    ///
    /// El image_id no es configurable por el caller: siempre se usa la constante
    /// AGENT_GUEST_ID hardcodeada en el contrato.
    ///
    /// ⚠️ RISC0_DEV_MODE=1 genera STARK receipts que NO se pueden verificar on-chain.
    ///    Usa Bonsai API para Groth16 en producción.
    pub fn verify_and_pay(
        ctx:             Context<VerifyAndPay>,
        seal:            Vec<u8>,
        journal_outputs: Vec<u8>,
    ) -> Result<()> {
        require!(
            ctx.accounts.job.status == JobStatus::PendingVerification,
            AgentMarketError::JobNotPendingVerification
        );

        // ── 1. Deserializar AuditJournal ──────────────────────────────────────
        let journal = AuditJournal::from_bytes(&journal_outputs)?;

        // ── 2. Verificar lógica de negocio antes de la CPI ───────────────────
        require!(
            journal.jobspec_hash == ctx.accounts.job.output_hash,
            AgentMarketError::ReportHashMismatch
        );
        require!(
            journal.auditor_pubkey == ctx.accounts.agent.key().to_bytes(),
            AgentMarketError::AuditorMismatch
        );

        // ── 3-4. CPI al Verifier Router (omitido con feature no-zk) ─────────────
        // no-zk: salta la verificación on-chain para pruebas en localnet.
        // Para mainnet: cargo build-sbf --no-default-features (elimina no-zk).
        #[cfg(not(feature = "no-zk"))]
        {
            let journal_digest = hashv(&[journal_outputs.as_slice()]).to_bytes();

            // image_id siempre es la constante hardcodeada — nunca proviene del caller.
            let mut ix_data = Vec::with_capacity(8 + seal.len() + 32 + 32);
            ix_data.extend_from_slice(&VERIFY_DISCRIMINATOR);
            ix_data.extend_from_slice(&seal);
            ix_data.extend_from_slice(&AGENT_GUEST_ID);
            ix_data.extend_from_slice(&journal_digest);

            let ix = Instruction {
                program_id: VERIFIER_ROUTER,
                accounts: vec![
                    AccountMeta::new_readonly(ctx.accounts.router_account.key(),  false),
                    AccountMeta::new_readonly(ctx.accounts.verifier_entry.key(),  false),
                    AccountMeta::new_readonly(ctx.accounts.verifier_program.key(),false),
                    AccountMeta::new_readonly(ctx.accounts.system_program.key(),  false),
                ],
                data: ix_data,
            };

            invoke(
                &ix,
                &[
                    ctx.accounts.router_account.to_account_info(),
                    ctx.accounts.verifier_entry.to_account_info(),
                    ctx.accounts.verifier_program.to_account_info(),
                    ctx.accounts.system_program.to_account_info(),
                ],
            ).map_err(|_| AgentMarketError::ProofInvalid)?;
        }

        #[cfg(feature = "no-zk")]
        let _ = &seal;

        // ── 5. Proof válido → pagar al auditor ────────────────────────────────
        let reward = ctx.accounts.job.reward;
        ctx.accounts.job.sub_lamports(reward)?;
        ctx.accounts.agent.add_lamports(reward)?;
        ctx.accounts.job.status = JobStatus::Completed;

        Ok(())
    }
}

// ── Contextos de cuentas ──────────────────────────────────────────────────────

#[derive(Accounts)]
pub struct CancelJob<'info> {
    #[account(mut, constraint = job.client == client.key())]
    pub client: Signer<'info>,

    #[account(
        mut,
        seeds = [b"job", client.key().as_ref(), &job.created_at.to_le_bytes()],
        bump = job.bump
    )]
    pub job: Account<'info, Job>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(input_hash: [u8; 32], output_hash: [u8; 32], reward: u64, created_at: i64)]
pub struct CreateJob<'info> {
    #[account(mut)]
    pub client: Signer<'info>,

    #[account(
        init,
        payer = client,
        space = 8 + 32 + 33 + 32 + 32 + 32 + 8 + 1 + 8 + 1,
        seeds = [b"job", client.key().as_ref(), &created_at.to_le_bytes()],
        bump
    )]
    pub job: Account<'info, Job>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(created_at: i64)]
pub struct ClaimJob<'info> {
    pub agent: Signer<'info>,

    #[account(
        mut,
        seeds = [b"job", client.key().as_ref(), &created_at.to_le_bytes()],
        bump = job.bump,
        constraint = job.client == client.key()
    )]
    pub job: Account<'info, Job>,

    /// CHECK: Solo para validar las seeds del PDA
    pub client: UncheckedAccount<'info>,
}

#[derive(Accounts)]
pub struct SubmitResult<'info> {
    pub agent: Signer<'info>,

    #[account(
        mut,
        seeds = [b"job", job.client.as_ref(), &job.created_at.to_le_bytes()],
        bump = job.bump,
        constraint = job.agent == Some(agent.key()) @ AgentMarketError::NotAssignedAgent
    )]
    pub job: Account<'info, Job>,
}

#[derive(Accounts)]
pub struct VerifyAndPay<'info> {
    #[account(
        mut,
        seeds = [b"job", job.client.as_ref(), &job.created_at.to_le_bytes()],
        bump = job.bump
    )]
    pub job: Account<'info, Job>,

    /// CHECK: Recibe el reward — verificado por journal.auditor_pubkey
    #[account(mut, constraint = job.agent == Some(agent.key()))]
    pub agent: UncheckedAccount<'info>,

    /// CHECK: Estado del VerifierRouter (PDA del programa RISC Zero)
    pub router_account: UncheckedAccount<'info>,

    /// CHECK: PDA que mapea seal.selector al verifier Groth16
    pub verifier_entry: UncheckedAccount<'info>,

    /// CHECK: El programa Groth16 verifier — validado internamente por el router
    pub verifier_program: UncheckedAccount<'info>,

    pub system_program: Program<'info, System>,
}
